name: Build

on:
  push:
    branches-ignore:
     - gh-pages
    paths:
      - package.json
      - package-lock.json
      - src/**
      - tsconfig.json
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Test build
      run: npm run build
