name: Publish to github npm registry

on:
  release:
    types: [published]
jobs:
  publish-types:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@lechaterrant'

    - name: Install dependencies
      run: npm install

    - name: Publish
      run: npm publish --tag $GITHUB_REF
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
