name: Publish package to npm registry

on:
  release:
    types: [published]
jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        # Needs to match the package.json name (@scope/pkg-name)
        scope: '@lechaterrant'

    - name: Install dependencies
      run: npm install

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
